Repository KodlabPenn/kodlab_mjbots_sdk, pull requests merged in 2022-07, with the labels that each got.

#17 Adds missing <tuple> include
  include/kodlab_mjbots_sdk/moteus_protocol.h
Labels: bug

#18 Moves JointBase zero offset from servo-space to joint-space
  src/joint_base.cpp
Labels: bug

#19 Joint base interfacing
  include/kodlab_mjbots_sdk/joint_base.h
Labels: documentation, enhancement

#24 adds simple mode input communication struct.
  lcm_types/mode_input.lcm
  python_scripts/mode_input_cli.py
Labels: enhancement

#20 Macro loggers
  README.md
  examples/leg_2DoF_example.cpp
  examples/leg_3DoF_example.cpp
  examples/proprio_example.cpp
  examples/spin_joints_example.cpp
  include/kodlab_mjbots_sdk/log.h
  src/CMakeLists.txt
Labels: enhancement

#13 adds live plotter python script
  python_scripts/blit_manager.py
  python_scripts/live_motor_plotter.py
Labels: enhancement
