Repository KodlabPenn/kodlab_mjbots_sdk, pull requests merged in 2022-08, with the labels that each got.

#16 Implementation of Attitude Class & Associated Math Headers
  examples/CMakeLists.txt
  examples/imu_example.cpp
  include/kodlab_mjbots_sdk/common_header.h
  include/kodlab_mjbots_sdk/imu_data.h
  include/kodlab_mjbots_sdk/math.h
  include/kodlab_mjbots_sdk/mjbots_control_loop.h
  include/kodlab_mjbots_sdk/mjbots_robot_interface.h
  include/kodlab_mjbots_sdk/pi3hat.h
  include/kodlab_mjbots_sdk/rotations.h
  lcm_types/imu_log.lcm
  src/CMakeLists.txt
  src/mjbots_robot_interface.cpp
  src/pi3hat.cpp
Labels: enhancement

#27 Added names and helper classes to joint base and moteus
  include/kodlab_mjbots_sdk/joint_base.h
  include/kodlab_mjbots_sdk/joint_moteus.h
  src/joint_base.cpp
Labels: enhancement

#30 adds shared_ptr overloads for mjbots constructors
  include/kodlab_mjbots_sdk/common_header.h
  include/kodlab_mjbots_sdk/mjbots_control_loop.h
  include/kodlab_mjbots_sdk/mjbots_robot_interface.h
  src/mjbots_robot_interface.cpp
Labels: enhancement

#31 Separate RobotBase from MJBotsInterface
  README.md
  examples/CMakeLists.txt
  examples/imu_example.cpp
  examples/leg_2DoF_example.cpp
  examples/leg_3DoF_example.cpp
  examples/proprio_example.cpp
  examples/robot_example.cpp
  examples/spin_joints_example.cpp
  include/examples/simple_robot.h
  include/kodlab_mjbots_sdk/common_header.h
  include/kodlab_mjbots_sdk/mjbots_control_loop.h
  include/kodlab_mjbots_sdk/mjbots_robot_interface.h
  include/kodlab_mjbots_sdk/robot_interface.h
  src/CMakeLists.txt
  src/mjbots_robot_interface.cpp
  src/robot_interface.cpp
Labels: enhancement

#38 Changing naming convention in RobotBase, MJBotsInterface, MJBotsControlLoop
  README.md
  examples/imu_example.cpp
  examples/leg_2DoF_example.cpp
  examples/leg_3DoF_example.cpp
  examples/proprio_example.cpp
  examples/robot_example.cpp
  examples/spin_joints_example.cpp
  include/examples/simple_robot.h
  include/kodlab_mjbots_sdk/mjbots_control_loop.h
  include/kodlab_mjbots_sdk/mjbots_hardware_interface.h
  include/kodlab_mjbots_sdk/robot_base.h
  src/CMakeLists.txt
  src/mjbots_hardware_interface.cpp
  src/robot_base.cpp
Labels: documentation, enhancement

#33 Doxyfile and assets
  .gitignore
  Doxyfile
  doc/img/kodlab.png
Labels: documentation, enhancement

#42 Adds virtual intitialization method to MjbotsControlLoop
  include/kodlab_mjbots_sdk/mjbots_control_loop.h
Labels: enhancement

#43 Moves JointBase to kodlab namespace (closes #25)
  include/kodlab_mjbots_sdk/joint_base.h
  src/joint_base.cpp
  src/robot_base.cpp
Labels: bug

#50 Lcm publisher
  examples/imu_example.cpp
  examples/leg_2DoF_example.cpp
  examples/leg_3DoF_example.cpp
  examples/proprio_example.cpp
  examples/robot_example.cpp
  examples/spin_joints_example.cpp
  include/kodlab_mjbots_sdk/lcm_publisher.h
  include/kodlab_mjbots_sdk/mjbots_control_loop.h
  src/CMakeLists.txt
Labels: enhancement

#47 Lcm multiple subscriber
  examples/leg_2DoF_example.cpp
  examples/robot_example.cpp
  include/kodlab_mjbots_sdk/lcm_message_handler.h
  include/kodlab_mjbots_sdk/lcm_subscriber.h
  include/kodlab_mjbots_sdk/mjbots_control_loop.h
  src/CMakeLists.txt
Labels: enhancement

#45 adds IMUData member to RobotBase
  include/examples/simple_robot.h
  include/kodlab_mjbots_sdk/mjbots_control_loop.h
  include/kodlab_mjbots_sdk/mjbots_hardware_interface.h
  include/kodlab_mjbots_sdk/robot_base.h
  src/mjbots_hardware_interface.cpp
Labels: enhancement, priority-high

#39 Abstract behavior class and example
  README.md
  include/examples/simple_control_io_behavior.h
  include/examples/simple_spin_joints_behavior.h
  include/kodlab_mjbots_sdk/behavior.h
  include/kodlab_mjbots_sdk/io_behavior.h
  include/kodlab_mjbots_sdk/off_behavior.h
  lcm_types/motor_log.lcm
  lcm_types/pd_gains.lcm
  src/CMakeLists.txt
Labels: enhancement, priority-high

#40 Behavior manager class
  README.md
  include/kodlab_mjbots_sdk/behavior_manager.h
  src/CMakeLists.txt
Labels: enhancement, priority-high

#52 Add channel selection to mode_input_cli.py
  python_scripts/mode_input_cli.py
Labels: enhancement, priority-low

#59 Implement dry run capability
  include/kodlab_mjbots_sdk/mjbots_control_loop.h
  include/kodlab_mjbots_sdk/mjbots_hardware_interface.h
  include/kodlab_mjbots_sdk/string.h
  src/CMakeLists.txt
  src/mjbots_hardware_interface.cpp
Labels: enhancement, priority-med

#41 Mjbots behavior loop and example
  README.md
  examples/CMakeLists.txt
  examples/behavior_robot_example.cpp
  include/kodlab_mjbots_sdk/mjbots_behavior_loop.h
  include/kodlab_mjbots_sdk/type_traits.h
  src/CMakeLists.txt
Labels: enhancement, priority-high

#60 Logging improvements
  README.md
  include/kodlab_mjbots_sdk/log.h
Labels: bug, enhancement, priority-low

#65 Inline LcmSubscriber implementation
  include/kodlab_mjbots_sdk/lcm_subscriber.h
Labels: bug, priority-high
